export const tnveds = [
  {
    value: "01",
    title: "01 Живые животные",
    titleEn: "01 Live animals",
    titleCn: "01 活动物",
    disabled: false,
    search: "01 Живые животные 01 Live animals 01 活动物",
  },
  {
    value: "02",
    title: "02 Мясо и субпродукты",
    titleEn: "02 Meat and edible offal",
    titleCn: "02 肉及食用杂碎",
    disabled: false,
    search: "02 Мясо и субпродукты 02 Meat and edible offal 02 肉及食用杂碎",
  },
  {
    value: "03",
    title: "03 Рыба и морепродукты",
    titleEn: "03 Fish and seafood",
    titleCn: "03 鱼及海产品",
    disabled: false,
    search: "03 Рыба и морепродукты 03 Fish and seafood 03 鱼及海产品",
  },
  {
    value: "04",
    title: "04 Молочная продукция, яйца, мед",
    titleEn: "04 Dairy products, eggs, honey",
    titleCn: "04 乳品、蛋品、蜂蜜",
    disabled: false,
    search:
      "04 Молочная продукция, яйца, мед 04 Dairy products, eggs, honey 04 乳品、蛋品、蜂蜜",
  },
  {
    value: "05",
    title: "05 Прочие животные продукты",
    titleEn: "05 Other animal products",
    titleCn: "05 其他动物产品",
    disabled: false,
    search:
      "05 Прочие животные продукты 05 Other animal products 05 其他动物产品",
  },
  {
    value: "06",
    title: "06 Живые растения",
    titleEn: "06 Live plants",
    titleCn: "06 活植物",
    disabled: false,
    search: "06 Живые растения 06 Live plants 06 活植物",
  },
  {
    value: "07",
    title: "07 Овощи, клубнеплоды и зернобобовые",
    titleEn: "07 Vegetables, tubers and legumes",
    titleCn: "07 蔬菜、块茎及豆类",
    disabled: false,
    search:
      "07 Овощи, клубнеплоды и зернобобовые 07 Vegetables, tubers and legumes 07 蔬菜、块茎及豆类",
  },
  {
    value: "08",
    title: "08 Фрукты и орехи",
    titleEn: "08 Fruits and nuts",
    titleCn: "08 水果及坚果",
    disabled: false,
    search: "08 Фрукты и орехи 08 Fruits and nuts 08 水果及坚果",
  },
  {
    value: "09",
    title: "09 Кофе, чай, пряности",
    titleEn: "09 Coffee, tea, spices",
    titleCn: "09 咖啡、茶、香料",
    disabled: false,
    search: "09 Кофе, чай, пряности 09 Coffee, tea, spices 09 咖啡、茶、香料",
  },
  {
    value: "10",
    title: "10 Зерно",
    titleEn: "10 Cereals",
    titleCn: "10 谷物",
    disabled: false,
    search: "10 Зерно 10 Cereals 10 谷物",
  },
  {
    value: "11",
    title: "11 Продукты перемола",
    titleEn: "11 Milling products",
    titleCn: "11 磨粉产品",
    disabled: false,
    search: "11 Продукты перемола 11 Milling products 11 磨粉产品",
  },
  {
    value: "12",
    title: "12 Маслосемена",
    titleEn: "12 Oilseeds",
    titleCn: "12 油籽",
    disabled: false,
    search: "12 Маслосемена 12 Oilseeds 12 油籽",
  },
  {
    value: "13",
    title: "13 Растительные экстракты",
    titleEn: "13 Vegetable extracts",
    titleCn: "13 植物提取物",
    disabled: false,
    search: "13 Растительные экстракты 13 Vegetable extracts 13 植物提取物",
  },
  {
    value: "14",
    title: "14 Прочие растительные продукты",
    titleEn: "14 Other vegetable products",
    titleCn: "14 其他植物产品",
    disabled: false,
    search:
      "14 Прочие растительные продукты 14 Other vegetable products 14 其他植物产品",
  },
  {
    value: "15",
    title: "15 Масла и жиры",
    titleEn: "15 Oils and fats",
    titleCn: "15 油脂",
    disabled: false,
    search: "15 Масла и жиры 15 Oils and fats 15 油脂",
  },
  {
    value: "16",
    title: "16 Готовые продукты из мяса и рыбы",
    titleEn: "16 Prepared meat and fish products",
    titleCn: "16 肉鱼制品",
    disabled: false,
    search:
      "16 Готовые продукты из мяса и рыбы 16 Prepared meat and fish products 16 肉鱼制品",
  },
  {
    value: "17",
    title: "17 Сахар и сахаристые изделия",
    titleEn: "17 Sugar and confectionery",
    titleCn: "17 糖及糖食",
    disabled: false,
    search:
      "17 Сахар и сахаристые изделия 17 Sugar and confectionery 17 糖及糖食",
  },
  {
    value: "18",
    title: "18 Какао и продукты из него",
    titleEn: "18 Cocoa and cocoa preparations",
    titleCn: "18 可可及可可制品",
    disabled: false,
    search:
      "18 Какао и продукты из него 18 Cocoa and cocoa preparations 18 可可及可可制品",
  },
  {
    value: "19",
    title: "19 Готовые продукты на основе муки",
    titleEn: "19 Flour-based preparations",
    titleCn: "19 面粉制品",
    disabled: false,
    search:
      "19 Готовые продукты на основе муки 19 Flour-based preparations 19 面粉制品",
  },
  {
    value: "20",
    title: "20 Плодоовощная продукция",
    titleEn: "20 Fruit and vegetable preparations",
    titleCn: "20 果蔬制品",
    disabled: false,
    search:
      "20 Плодоовощная продукция 20 Fruit and vegetable preparations 20 果蔬制品",
  },
  {
    value: "21",
    title: "21 Разные пищевые продукты",
    titleEn: "21 Miscellaneous food preparations",
    titleCn: "21 杂项食品",
    disabled: false,
    search:
      "21 Разные пищевые продукты 21 Miscellaneous food preparations 21 杂项食品",
  },
  {
    value: "22",
    title: "22 Вода, напитки, спирт",
    titleEn: "22 Beverages, spirits and vinegar",
    titleCn: "22 饮料、酒及醋",
    disabled: false,
    search:
      "22 Вода, напитки, спирт 22 Beverages, spirits and vinegar 22 饮料、酒及醋",
  },
  {
    value: "23",
    title: "23 Корма",
    titleEn: "23 Animal feed",
    titleCn: "23 饲料",
    disabled: false,
    search: "23 Корма 23 Animal feed 23 饲料",
  },
  {
    value: "24",
    title: "24 Табак",
    titleEn: "24 Tobacco",
    titleCn: "24 烟草",
    disabled: false,
    search: "24 Табак 24 Tobacco 24 烟草",
  },
  {
    value: "25",
    title: "25 Нерудное минеральное сырье",
    titleEn: "25 Salt, stone and earth",
    titleCn: "25 盐、石料及泥土",
    disabled: false,
    search:
      "25 Нерудное минеральное сырье 25 Salt, stone and earth 25 盐、石料及泥土",
  },
  {
    value: "26",
    title: "26 Руды",
    titleEn: "26 Ores",
    titleCn: "26 矿砂",
    disabled: false,
    search: "26 Руды 26 Ores 26 矿砂",
  },
  {
    value: "27",
    title: "27 Топливо",
    titleEn: "27 Mineral fuels",
    titleCn: "27 矿物燃料",
    disabled: false,
    search: "27 Топливо 27 Mineral fuels 27 矿物燃料",
  },
  {
    value: "28",
    title: "28 Продукты неорганической химии",
    titleEn: "28 Inorganic chemicals",
    titleCn: "28 无机化学品",
    disabled: false,
    search:
      "28 Продукты неорганической химии 28 Inorganic chemicals 28 无机化学品",
  },
  {
    value: "29",
    title: "29 Продукты органической химии",
    titleEn: "29 Organic chemicals",
    titleCn: "29 有机化学品",
    disabled: false,
    search: "29 Продукты органической химии 29 Organic chemicals 29 有机化学品",
  },
  {
    value: "30",
    title: "30 Фармацевтическая продукция",
    titleEn: "30 Pharmaceutical products",
    titleCn: "30 药品",
    disabled: false,
    search: "30 Фармацевтическая продукция 30 Pharmaceutical products 30 药品",
  },
  {
    value: "31",
    title: "31 Удобрения",
    titleEn: "31 Fertilizers",
    titleCn: "31 肥料",
    disabled: false,
    search: "31 Удобрения 31 Fertilizers 31 肥料",
  },
  {
    value: "32",
    title: "32 Лакокрасочная продукция",
    titleEn: "32 Paints and varnishes",
    titleCn: "32 油漆及清漆",
    disabled: false,
    search: "32 Лакокрасочная продукция 32 Paints and varnishes 32 油漆及清漆",
  },
  {
    value: "33",
    title: "33 Парфюмерные, косметические и туалетные средства",
    titleEn: "33 Perfumes and cosmetics",
    titleCn: "33 香水及化妆品",
    disabled: false,
    search:
      "33 Парфюмерные, косметические и туалетные средства 33 Perfumes and cosmetics 33 香水及化妆品",
  },
  {
    value: "34",
    title: "34 Моющие средства и смазочные материалы",
    titleEn: "34 Soaps and lubricants",
    titleCn: "34 肥皂及润滑剂",
    disabled: false,
    search:
      "34 Моющие средства и смазочные материалы 34 Soaps and lubricants 34 肥皂及润滑剂",
  },
  {
    value: "35",
    title: "35 Белковые вещества, клеи, ферменты",
    titleEn: "35 Albuminoids, glues, enzymes",
    titleCn: "35 蛋白类物质、胶、酶",
    disabled: false,
    search:
      "35 Белковые вещества, клеи, ферменты 35 Albuminoids, glues, enzymes 35 蛋白类物质、胶、酶",
  },
  {
    value: "36",
    title: "36 Пиротехника",
    titleEn: "36 Explosives",
    titleCn: "36 炸药",
    disabled: false,
    search: "36 Пиротехника 36 Explosives 36 炸药",
  },
  {
    value: "37",
    title: "37 Фото- и кинотовары",
    titleEn: "37 Photographic goods",
    titleCn: "37 照相及电影用品",
    disabled: false,
    search: "37 Фото- и кинотовары 37 Photographic goods 37 照相及电影用品",
  },
  {
    value: "38",
    title: "38 Прочие химические продукты",
    titleEn: "38 Miscellaneous chemical products",
    titleCn: "38 杂项化学产品",
    disabled: false,
    search:
      "38 Прочие химические продукты 38 Miscellaneous chemical products 38 杂项化学产品",
  },
  {
    value: "39",
    title: "39 Пластмассы и изделия из них",
    titleEn: "39 Plastics and articles thereof",
    titleCn: "39 塑料及其制品",
    disabled: false,
    search:
      "39 Пластмассы и изделия из них 39 Plastics and articles thereof 39 塑料及其制品",
  },
  {
    value: "40",
    title: "40 Каучук и резинотехнические изделия",
    titleEn: "40 Rubber and rubber articles",
    titleCn: "40 橡胶及其制品",
    disabled: false,
    search:
      "40 Каучук и резинотехнические изделия 40 Rubber and rubber articles 40 橡胶及其制品",
  },
  {
    value: "41",
    title: "41 Шкуры и кожа",
    titleEn: "41 Raw hides and skins",
    titleCn: "41 生皮及皮革",
    disabled: false,
    search: "41 Шкуры и кожа 41 Raw hides and skins 41 生皮及皮革",
  },
  {
    value: "42",
    title: "42 Изделия из кожи, дорожные принадлежности",
    titleEn: "42 Leather articles, travel goods",
    titleCn: "42 皮革制品、旅行用品",
    disabled: false,
    search:
      "42 Изделия из кожи, дорожные принадлежности 42 Leather articles, travel goods 42 皮革制品、旅行用品",
  },
  {
    value: "43",
    title: "43 Мех",
    titleEn: "43 Furskins",
    titleCn: "43 毛皮",
    disabled: false,
    search: "43 Мех 43 Furskins 43 毛皮",
  },
  {
    value: "44",
    title: "44 Древесина и продукция деревообработки",
    titleEn: "44 Wood and wood articles",
    titleCn: "44 木及木制品",
    disabled: false,
    search:
      "44 Древесина и продукция деревообработки 44 Wood and wood articles 44 木及木制品",
  },
  {
    value: "45",
    title: "45 Пробка",
    titleEn: "45 Cork",
    titleCn: "45 软木",
    disabled: false,
    search: "45 Пробка 45 Cork 45 软木",
  },
  {
    value: "46",
    title: "46 Плетеные изделия",
    titleEn: "46 Manufactures of straw",
    titleCn: "46 编结材料制品",
    disabled: false,
    search: "46 Плетеные изделия 46 Manufactures of straw 46 编结材料制品",
  },
  {
    value: "47",
    title: "47 Целлюлоза",
    titleEn: "47 Pulp",
    titleCn: "47 木浆",
    disabled: false,
    search: "47 Целлюлоза 47 Pulp 47 木浆",
  },
  {
    value: "48",
    title: "48 Бумага и картон",
    titleEn: "48 Paper and paperboard",
    titleCn: "48 纸及纸板",
    disabled: false,
    search: "48 Бумага и картон 48 Paper and paperboard 48 纸及纸板",
  },
  {
    value: "49",
    title: "49 Полиграфическая продукция",
    titleEn: "49 Printed matter",
    titleCn: "49 印刷品",
    disabled: false,
    search: "49 Полиграфическая продукция 49 Printed matter 49 印刷品",
  },
  {
    value: "50",
    title: "50 Шелк и продукция из него",
    titleEn: "50 Silk",
    titleCn: "50 蚕丝",
    disabled: false,
    search: "50 Шелк и продукция из него 50 Silk 50 蚕丝",
  },
  {
    value: "51",
    title: "51 Шерсть и продукция из нее",
    titleEn: "51 Wool",
    titleCn: "51 羊毛",
    disabled: false,
    search: "51 Шерсть и продукция из нее 51 Wool 51 羊毛",
  },
  {
    value: "52",
    title: "52 Хлопок и продукция из него",
    titleEn: "52 Cotton",
    titleCn: "52 棉花",
    disabled: false,
    search: "52 Хлопок и продукция из него 52 Cotton 52 棉花",
  },
  {
    value: "53",
    title: "53 Прочие текстильные волокна",
    titleEn: "53 Other vegetable textile fibers",
    titleCn: "53 其他植物纺织纤维",
    disabled: false,
    search:
      "53 Прочие текстильные волокна 53 Other vegetable textile fibers 53 其他植物纺织纤维",
  },
  {
    value: "54",
    title: "54 Химические нити и ткани из них",
    titleEn: "54 Man-made filaments",
    titleCn: "54 化学纤维长丝",
    disabled: false,
    search:
      "54 Химические нити и ткани из них 54 Man-made filaments 54 化学纤维长丝",
  },
  {
    value: "55",
    title: "55 Химические волокна и ткани из них",
    titleEn: "55 Man-made staple fibers",
    titleCn: "55 化学纤维短纤",
    disabled: false,
    search:
      "55 Химические волокна и ткани из них 55 Man-made staple fibers 55 化学纤维短纤",
  },
  {
    value: "56",
    title: "56 Нетканые материалы",
    titleEn: "56 Wadding and nonwovens",
    titleCn: "56 絮胎及无纺物",
    disabled: false,
    search: "56 Нетканые материалы 56 Wadding and nonwovens 56 絮胎及无纺物",
  },
  {
    value: "57",
    title: "57 Текстильные напольные покрытия",
    titleEn: "57 Carpets",
    titleCn: "57 地毯",
    disabled: false,
    search: "57 Текстильные напольные покрытия 57 Carpets 57 地毯",
  },
  {
    value: "58",
    title: "58 Специальные ткани",
    titleEn: "58 Special woven fabrics",
    titleCn: "58 特种机织物",
    disabled: false,
    search: "58 Специальные ткани 58 Special woven fabrics 58 特种机织物",
  },
  {
    value: "59",
    title: "59 Текстиль технического назначения",
    titleEn: "59 Technical textiles",
    titleCn: "59 工业用纺织品",
    disabled: false,
    search:
      "59 Текстиль технического назначения 59 Technical textiles 59 工业用纺织品",
  },
  {
    value: "60",
    title: "60 Трикотажные полотна",
    titleEn: "60 Knitted fabrics",
    titleCn: "60 针织物",
    disabled: false,
    search: "60 Трикотажные полотна 60 Knitted fabrics 60 针织物",
  },
  {
    value: "61",
    title: "61 Одежда трикотажная",
    titleEn: "61 Knitted apparel",
    titleCn: "61 针织服装",
    disabled: false,
    search: "61 Одежда трикотажная 61 Knitted apparel 61 针织服装",
  },
  {
    value: "62",
    title: "62 Одежда швейная",
    titleEn: "62 Woven apparel",
    titleCn: "62 非针织服装",
    disabled: false,
    search: "62 Одежда швейная 62 Woven apparel 62 非针织服装",
  },
  {
    value: "63",
    title: "63 Готовые текстильные изделия",
    titleEn: "63 Made-up textiles",
    titleCn: "63 其他纺织制成品",
    disabled: false,
    search:
      "63 Готовые текстильные изделия 63 Made-up textiles 63 其他纺织制成品",
  },
  {
    value: "64",
    title: "64 Обувь",
    titleEn: "64 Footwear",
    titleCn: "64 鞋靴",
    disabled: false,
    search: "64 Обувь 64 Footwear 64 鞋靴",
  },
  {
    value: "65",
    title: "65 Головные уборы",
    titleEn: "65 Headgear",
    titleCn: "65 帽类",
    disabled: false,
    search: "65 Головные уборы 65 Headgear 65 帽类",
  },
  {
    value: "66",
    title: "66 Зонты, трости",
    titleEn: "66 Umbrellas, walking sticks",
    titleCn: "66 伞、手杖",
    disabled: false,
    search: "66 Зонты, трости 66 Umbrellas, walking sticks 66 伞、手杖",
  },
  {
    value: "67",
    title: "67 Изделия из перьев, пуха, волоса",
    titleEn: "67 Feathers, down, artificial flowers",
    titleCn: "67 羽毛、羽绒制品",
    disabled: false,
    search:
      "67 Изделия из перьев, пуха, волоса 67 Feathers, down, artificial flowers 67 羽毛、羽绒制品",
  },
  {
    value: "68",
    title: "68 Изделия из минералов",
    titleEn: "68 Stone, plaster, cement articles",
    titleCn: "68 石料、石膏、水泥制品",
    disabled: false,
    search:
      "68 Изделия из минералов 68 Stone, plaster, cement articles 68 石料、石膏、水泥制品",
  },
  {
    value: "69",
    title: "69 Керамические изделия",
    titleEn: "69 Ceramic products",
    titleCn: "69 陶瓷产品",
    disabled: false,
    search: "69 Керамические изделия 69 Ceramic products 69 陶瓷产品",
  },
  {
    value: "70",
    title: "70 Стекло и изделия из него",
    titleEn: "70 Glass and glassware",
    titleCn: "70 玻璃及其制品",
    disabled: false,
    search:
      "70 Стекло и изделия из него 70 Glass and glassware 70 玻璃及其制品",
  },
  {
    value: "71",
    title: "71 Драгоценные металлы и камни",
    titleEn: "71 Pearls, precious metals",
    titleCn: "71 珍珠、贵金属",
    disabled: false,
    search:
      "71 Драгоценные металлы и камни 71 Pearls, precious metals 71 珍珠、贵金属",
  },
  {
    value: "72",
    title: "72 Черные металлы",
    titleEn: "72 Iron and steel",
    titleCn: "72 钢铁",
    disabled: false,
    search: "72 Черные металлы 72 Iron and steel 72 钢铁",
  },
  {
    value: "73",
    title: "73 Изделия из черных металлов",
    titleEn: "73 Iron or steel articles",
    titleCn: "73 钢铁制品",
    disabled: false,
    search:
      "73 Изделия из черных металлов 73 Iron or steel articles 73 钢铁制品",
  },
  {
    value: "74",
    title: "74 Медь",
    titleEn: "74 Copper",
    titleCn: "74 铜",
    disabled: false,
    search: "74 Медь 74 Copper 74 铜",
  },
  {
    value: "75",
    title: "75 Никель",
    titleEn: "75 Nickel",
    titleCn: "75 镍",
    disabled: false,
    search: "75 Никель 75 Nickel 75 镍",
  },
  {
    value: "76",
    title: "76 Алюминий",
    titleEn: "76 Aluminum",
    titleCn: "76 铝",
    disabled: false,
    search: "76 Алюминий 76 Aluminum 76 铝",
  },
  {
    value: "78",
    title: "78 Свинец",
    titleEn: "78 Lead",
    titleCn: "78 铅",
    disabled: false,
    search: "78 Свинец 78 Lead 78 铅",
  },
  {
    value: "79",
    title: "79 Цинк",
    titleEn: "79 Zinc",
    titleCn: "79 锌",
    disabled: false,
    search: "79 Цинк 79 Zinc 79 锌",
  },
  {
    value: "80",
    title: "80 Олово",
    titleEn: "80 Tin",
    titleCn: "80 锡",
    disabled: false,
    search: "80 Олово 80 Tin 80 锡",
  },
  {
    value: "81",
    title: "81 Прочие недрагоценные металлы",
    titleEn: "81 Other base metals",
    titleCn: "81 其他贱金属",
    disabled: false,
    search:
      "81 Прочие недрагоценные металлы 81 Other base metals 81 其他贱金属",
  },
  {
    value: "82",
    title: "82 Инструменты и столовые приборы",
    titleEn: "82 Tools and cutlery",
    titleCn: "82 工具及餐具",
    disabled: false,
    search:
      "82 Инструменты и столовые приборы 82 Tools and cutlery 82 工具及餐具",
  },
  {
    value: "83",
    title: "83 Прочие металлоизделия",
    titleEn: "83 Miscellaneous metal articles",
    titleCn: "83 杂项金属制品",
    disabled: false,
    search:
      "83 Прочие металлоизделия 83 Miscellaneous metal articles 83 杂项金属制品",
  },
  {
    value: "84",
    title: "84 Механическое оборудование и техника, компьютеры",
    titleEn: "84 Machinery, computers",
    titleCn: "84 机械设备、计算机",
    disabled: false,
    search:
      "84 Механическое оборудование и техника, компьютеры 84 Machinery, computers 84 机械设备、计算机",
  },
  {
    value: "85",
    title: "85 Электрические устройства, аппаратура связи",
    titleEn: "85 Electrical machinery, telecom",
    titleCn: "85 电机、电气设备",
    disabled: false,
    search:
      "85 Электрические устройства, аппаратура связи 85 Electrical machinery, telecom 85 电机、电气设备",
  },
  {
    value: "86",
    title: "86 Железнодорожная техника",
    titleEn: "86 Railway vehicles",
    titleCn: "86 铁道车辆",
    disabled: false,
    search: "86 Железнодорожная техника 86 Railway vehicles 86 铁道车辆",
  },
  {
    value: "87",
    title: "87 Автотехника",
    titleEn: "87 Vehicles",
    titleCn: "87 汽车",
    disabled: false,
    search: "87 Автотехника 87 Vehicles 87 汽车",
  },
  {
    value: "88",
    title: "88 Летательные аппараты",
    titleEn: "88 Aircraft",
    titleCn: "88 航空器",
    disabled: false,
    search: "88 Летательные аппараты 88 Aircraft 88 航空器",
  },
  {
    value: "89",
    title: "89 Суда и плавсредства",
    titleEn: "89 Ships and boats",
    titleCn: "89 船舶",
    disabled: false,
    search: "89 Суда и плавсредства 89 Ships and boats 89 船舶",
  },
  {
    value: "90",
    title: "90 Оптика, приборы, медицинская техника",
    titleEn: "90 Optical, medical instruments",
    titleCn: "90 光学、医疗仪器",
    disabled: false,
    search:
      "90 Оптика, приборы, медицинская техника 90 Optical, medical instruments 90 光学、医疗仪器",
  },
  {
    value: "91",
    title: "91 Часы",
    titleEn: "91 Clocks and watches",
    titleCn: "91 钟表",
    disabled: false,
    search: "91 Часы 91 Clocks and watches 91 钟表",
  },
  {
    value: "92",
    title: "92 Музыкальные инструменты",
    titleEn: "92 Musical instruments",
    titleCn: "92 乐器",
    disabled: false,
    search: "92 Музыкальные инструменты 92 Musical instruments 92 乐器",
  },
  {
    value: "93",
    title: "93 Оружие и боеприпасы",
    titleEn: "93 Arms and ammunition",
    titleCn: "93 武器弹药",
    disabled: false,
    search: "93 Оружие и боеприпасы 93 Arms and ammunition 93 武器弹药",
  },
  {
    value: "94",
    title: "94 Мебель, осветительная техника",
    titleEn: "94 Furniture, lighting",
    titleCn: "94 家具、灯具",
    disabled: false,
    search:
      "94 Мебель, осветительная техника 94 Furniture, lighting 94 家具、灯具",
  },
  {
    value: "95",
    title: "95 Игрушки и спортинвентарь",
    titleEn: "95 Toys, sports equipment",
    titleCn: "95 玩具、运动用品",
    disabled: false,
    search:
      "95 Игрушки и спортинвентарь 95 Toys, sports equipment 95 玩具、运动用品",
  },
  {
    value: "96",
    title: "96 Разные промтовары",
    titleEn: "96 Miscellaneous manufactures",
    titleCn: "96 杂项制品",
    disabled: false,
    search: "96 Разные промтовары 96 Miscellaneous manufactures 96 杂项制品",
  },
  {
    value: "97",
    title: "97 Произведения искусства",
    titleEn: "97 Works of art",
    titleCn: "97 艺术品",
    disabled: false,
    search: "97 Произведения искусства 97 Works of art 97 艺术品",
  },
];
export const country = [
  {
    value: "076",
    title: "Бразилия",
    titleEn: "Brazil",
    titleCn: "巴西",
    search:
      "Бразилия\\nФедеративная Республика Бразилия\\nBrazil\\nBR\\nBRA\\nFederative Republic of Brazil\\n076\\n\\n076",
    alpha2: "BR",
    disabled: false,
    friend: true,
  },
  {
    value: "356",
    title: "Индия",
    titleEn: "India",
    titleCn: "印度",
    search:
      "Индия\\nРеспублика Индия\\nIndia\\nIN\\nIND\\nRepublic of India\\n356\\n\\n356",
    alpha2: "IN",
    disabled: false,
    friend: true,
  },
  {
    value: "156",
    title: "Китай",
    titleEn: "China",
    titleCn: "中国",
    search:
      "Китай\\nКитайская Народная Республика\\nChina\\nCN\\nCHN\\nPeople's Republic of China\\n156\\nКНР",
    alpha2: "CN",
    disabled: false,
    friend: true,
  },
  {
    value: "710",
    title: "ЮАР",
    titleEn: "South Africa",
    titleCn: "南非",
    search:
      "ЮАР\\nЮжно-Африканская Республика\\nSouth Africa\\nZA\\nZAF\\nRepublic of South Africa\\n710\\n\\n710",
    alpha2: "ZA",
    disabled: false,
    friend: true,
  },
  {
    value: "364",
    title: "Иран",
    titleEn: "Iran",
    titleCn: "伊朗",
    search:
      "Иран\\nИсламская Республика Иран\\nIran\\nIR\\nIRN\\nIslamic Republic of Iran\\n364\\n\\n364",
    alpha2: "IR",
    disabled: false,
    friend: true,
  },
  {
    value: "818",
    title: "Египет",
    titleEn: "Egypt",
    titleCn: "埃及",
    search:
      "Египет\\nАрабская Республика Египет\\nEgypt\\nEG\\nEGY\\nArab Republic of Egypt\\n818\\n\\n818",
    alpha2: "EG",
    disabled: false,
    friend: true,
  },
  {
    value: "231",
    title: "Эфиопия",
    titleEn: "Ethiopia",
    titleCn: "埃塞俄比亚",
    search:
      "Эфиопия\\nФедеративная Демократическая Республика Эфиопия\\nEthiopia\\nET\\nETH\\nFederal Democratic Republic of Ethiopia\\n231\\n\\n231",
    alpha2: "ET",
    disabled: false,
    friend: true,
  },
  {
    value: "784",
    title: "ОАЭ",
    titleEn: "United Arab Emirates",
    titleCn: "阿拉伯联合酋长国",
    search:
      "ОАЭ\\nОбъединенные Арабские Эмираты\\nUnited Arab Emirates\\nAE\\nARE\\nUnited Arab Emirates\\n784\\n\\n784",
    alpha2: "AE",
    disabled: false,
    friend: true,
  },
  {
    value: "360",
    title: "Индонезия",
    titleEn: "Indonesia",
    titleCn: "印度尼西亚",
    search:
      "Индонезия\\nРеспублика Индонезия\\nIndonesia\\nID\\nIDN\\nRepublic of Indonesia\\n360\\n\\n360",
    alpha2: "ID",
    disabled: false,
    friend: true,
  },
];
